# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='companies_images')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('tagline', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('CEO_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('web_site', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('phone_number', models.CharField(default=None, max_length=64)),
                ('location', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('facebook_profile', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('twitter_profile', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('linkedin_profile', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('google_plus_profile', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('instagram_profile', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('dr_profile', models.URLField(blank=True, default=None, max_length=64, null=True)),
                ('about', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Company Category',
                'verbose_name_plural': 'Company Categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('requirement', models.TextField(blank=True, default=None, null=True)),
                ('dedline', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='companies.Companies')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Job Type',
                'verbose_name_plural': 'Job Types',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.JobType'),
        ),
        migrations.AddField(
            model_name='companies',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCategory'),
        ),
    ]
